Updated workflow to call ARM.

diff --git a/.github/workflows/deploy-to-prod.yaml b/.github/workflows/deploy-to-prod.yaml
--- a/.github/workflows/deploy-to-prod.yaml
+++ b/.github/workflows/deploy-to-prod.yaml
@@ -15,6 +15,14 @@ on:
         description: "Planned End Date Time (UTC), Format: YYYY-mm-DDTHH:MM:SSZ => 2026-08-12T20:30:00Z"
         type: string
         required: true
+      environment:
+        description: "Environment to deploy to"
+        type: choice
+        required: true
+        default: "PROD"
+        options:
+          - PROD
+          - DEV
       release_note:
         description: "Confluence link to release notes"
         type: string
@@ -24,19 +32,25 @@ on:
 jobs:
   generate-release-tag:
     uses: ./.github/workflows/generate-release-tag.yaml
+    with:
+      short_description: ${{ inputs.short_description }}
+      planned_startdate: ${{ inputs.planned_startdate }}
+      planned_enddate: ${{ inputs.planned_enddate }}
+      release_note: ${{ inputs.release_note }}
+      environment: ${{ inputs.environment }}
     secrets: inherit
 
-  notify-release-tag-gen-finished:
-    if: success() || failure() || cancelled()
-    uses: ./.github/workflows/notify-events-new.yaml
-    needs: generate-release-tag
-    with:
-      state: ${{ needs.generate-release-tag.result }}
-      release_tag: ${{ needs.generate-release-tag.outputs.release_tag}}
-      title: "CD: ${{ github.repository }}: <b>Release tag generation finished.</b>"
-      message: "<b>PROD Deployment:</b> Release tag generation finished with state <b>${{ needs.generate-release-tag.result }}.</b>"
-    secrets:
-      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
+  # notify-release-tag-gen-finished:
+  #   if: success() || failure() || cancelled()
+  #   uses: ./.github/workflows/notify-events-new.yaml
+  #   needs: generate-release-tag
+  #   with:
+  #     state: ${{ needs.generate-release-tag.result }}
+  #     release_tag: ${{ needs.generate-release-tag.outputs.release_tag}}
+  #     title: "CD: ${{ github.repository }}: <b>Release tag generation finished.</b>"
+  #     message: "<b>PROD Deployment:</b> Release tag generation finished with state <b>${{ needs.generate-release-tag.result }}.</b>"
+  #   secrets:
+  #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
 
   build-publish-docker:
     needs: generate-release-tag
@@ -45,11 +59,11 @@ jobs:
       - name: Print release tag
         run: echo "Release Tag = ${{ needs.generate-release-tag.outputs.release_tag}}"
 
-      # - name: Login to Docker Hub
-      #   uses: docker/login-action@v3
-      #   with:
-      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       # - name: Set up QEMU
       #   uses: docker/setup-qemu-action@v3
@@ -63,20 +77,24 @@ jobs:
       #     push: true
       #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/glow-portals:${{ needs.generate-release-tag.outputs.release_tag }}
 
-      - name: Pass release_tag to next job
-        run: echo "release_tag=${{ needs.generate-release-tag.outputs.release_tag }}" >> "$GITHUB_OUTPUT"
 
-  notify-build-publish-docker-finished:
-    if: success() || failure() || cancelled()
-    uses: ./.github/workflows/notify-events-new.yaml
-    needs: [generate-release-tag, build-publish-docker]
-    with:
-      state: ${{ needs.build-publish-docker.result }}
-      release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
-      title: "CD: ${{ github.repository }}: <b>Build publish to docker finished.</b>"
-      message: "<b>PROD Deployment:</b> Build publish to docker finished with state <b>${{ needs.build-publish-docker.result }}.</b>"
-    secrets:
-      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
+
+      
+
+      # - name: Pass release_tag to next job
+      #   run: echo "release_tag=${{ needs.generate-release-tag.outputs.release_tag }}" >> "$GITHUB_OUTPUT"
+
+  # notify-build-publish-docker-finished:
+  #   if: success() || failure() || cancelled()
+  #   uses: ./.github/workflows/notify-events-new.yaml
+  #   needs: [generate-release-tag, build-publish-docker]
+  #   with:
+  #     state: ${{ needs.build-publish-docker.result }}
+  #     release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
+  #     title: "CD: ${{ github.repository }}: <b>Build publish to docker finished.</b>"
+  #     message: "<b>PROD Deployment:</b> Build publish to docker finished with state <b>${{ needs.build-publish-docker.result }}.</b>"
+  #   secrets:
+  #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
 
   chart-tagger:
     needs: [generate-release-tag, build-publish-docker]
@@ -93,93 +111,93 @@ jobs:
                   "event_type": "helm_chart_image_tag_update",
                   "client_payload": {
                   "release_tag": "${{ needs.generate-release-tag.outputs.release_tag }}",
-                  "chr": "${{ inputs.cr }}",
+                  "release_id": "${{ needs.generate-release-tag.outputs.release_id }}",
                   "release_note": "${{ inputs.release_note }}"
                   }
               }')
               echo "Response: $response"
 
-  notify-chart-tagger-finished:
-    if: success() || failure() || cancelled()
-    uses: ./.github/workflows/notify-events-new.yaml
-    needs: [generate-release-tag, chart-tagger]
-    with:
-      state: ${{ needs.chart-tagger.result }}
-      release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
-      title: "CD: ${{ github.repository }}: <b>Chart tagger finished.</b>"
-      message: "<b>PROD Deployment:</b> Chart tagger finished with state <b>${{ needs.chart-tagger.result }}.</b>"
-    secrets:
-      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
+  # notify-chart-tagger-finished:
+  #   if: success() || failure() || cancelled()
+  #   uses: ./.github/workflows/notify-events-new.yaml
+  #   needs: [generate-release-tag, chart-tagger]
+  #   with:
+  #     state: ${{ needs.chart-tagger.result }}
+  #     release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
+  #     title: "CD: ${{ github.repository }}: <b>Chart tagger finished.</b>"
+  #     message: "<b>PROD Deployment:</b> Chart tagger finished with state <b>${{ needs.chart-tagger.result }}.</b>"
+  #   secrets:
+  #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
 
-  port-logs:
-    if: success() || failure() || cancelled()
-    needs: [generate-release-tag, build-publish-docker, chart-tagger]
-    uses: ./.github/workflows/post-logs-to-elastic.yaml
-    with:
-      release_tag: ${{ needs.generate-release-tag.outputs.release_tag}}
-      helm_env: "prod"
-    secrets:
-      ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
-      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
-      ELASTIC_INDEX: ${{ secrets.ELASTIC_INDEX }}
+  # port-logs:
+  #   if: success() || failure() || cancelled()
+  #   needs: [generate-release-tag, build-publish-docker, chart-tagger]
+  #   uses: ./.github/workflows/post-logs-to-elastic.yaml
+  #   with:
+  #     release_tag: ${{ needs.generate-release-tag.outputs.release_tag}}
+  #     helm_env: "prod"
+  #   secrets:
+  #     ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
+  #     ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
+  #     ELASTIC_INDEX: ${{ secrets.ELASTIC_INDEX }}
 
-  notify-port-logs-finished:
-    if: success() || failure() || cancelled()
-    uses: ./.github/workflows/notify-events-new.yaml
-    needs: [generate-release-tag, port-logs]
-    with:
-      state: ${{ needs.port-logs.result }}
-      release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
-      title: "CD: ${{ github.repository }}: <b>Port logs finished.</b>"
-      message: "<b>PROD Deployment:</b> Port logs finished with state <b>${{ needs.port-logs.result }}.</b>"
-    secrets:
-      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
+  # notify-port-logs-finished:
+  #   if: success() || failure() || cancelled()
+  #   uses: ./.github/workflows/notify-events-new.yaml
+  #   needs: [generate-release-tag, port-logs]
+  #   with:
+  #     state: ${{ needs.port-logs.result }}
+  #     release_tag: ${{ needs.generate-release-tag.outputs.release_tag }}
+  #     title: "CD: ${{ github.repository }}: <b>Port logs finished.</b>"
+  #     message: "<b>PROD Deployment:</b> Port logs finished with state <b>${{ needs.port-logs.result }}.</b>"
+  #   secrets:
+  #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
 
-  workflow-summary:
-    name: Compute overall workflow state
-    runs-on: ubuntu-latest
-    needs: [generate-release-tag, build-publish-docker, chart-tagger, port-logs]
-    if: always()
-    outputs:
-      state: ${{ steps.overall.outputs.state }}
-    steps:
-      - id: overall
-        shell: bash
-        run: |
-          RESULTS="${{ join(needs.*.result, ',') }}"
-          echo "Results: $RESULTS"
+  # workflow-summary:
+  #   name: Compute overall workflow state
+  #   runs-on: ubuntu-latest
+  #   needs: [generate-release-tag, build-publish-docker, chart-tagger, port-logs]
+  #   if: always()
+  #   outputs:
+  #     state: ${{ steps.overall.outputs.state }}
+  #   steps:
+  #     - id: overall
+  #       shell: bash
+  #       run: |
+  #         RESULTS="${{ join(needs.*.result, ',') }}"
+  #         echo "Results: $RESULTS"
 
-          if echo "$RESULTS" | grep -q "failure"; then
-            echo "state=failure" >> $GITHUB_OUTPUT
-          elif echo "$RESULTS" | grep -q "cancelled"; then
-            echo "state=cancelled" >> $GITHUB_OUTPUT
-          else
-            echo "state=success" >> $GITHUB_OUTPUT
-          fi
+  #         if echo "$RESULTS" | grep -q "failure"; then
+  #           echo "state=failure" >> $GITHUB_OUTPUT
+  #         elif echo "$RESULTS" | grep -q "cancelled"; then
+  #           echo "state=cancelled" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "state=success" >> $GITHUB_OUTPUT
+  #         fi
 
-  notify-workflow-status:
-    name: notify overall workflow result
-    needs:
-      [
-        workflow-summary,
-        generate-release-tag,
-        build-publish-docker,
-        chart-tagger,
-        port-logs,
-      ]
-    if: always()
-    uses: ./.github/workflows/notify-events-new.yaml
-    with:
-      state: ${{ needs.workflow-summary.outputs.state }}
-      title: "CD: ${{ github.repository }} - Workflow completed"
-      message: >
-        Workflow: ${{ github.workflow }}
-        Run: ${{ github.run_id }}
-        Actor: ${{ github.triggering_actor || github.actor }}
-        Result:
-        generate-release-tag=${{ needs.generate-release-tag.result }},
-        build-publish-docker=${{ needs.build-publish-docker.result }},
-        chart-tagger=${{ needs.chart-tagger.result }},
-        port-logs=${{ needs.port-logs.result }}
-    secrets:
-      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
+  # notify-workflow-status:
+  #   name: notify overall workflow result
+  #   needs:
+  #     [
+  #       workflow-summary,
+  #       generate-release-tag,
+  #       build-publish-docker,
+  #       chart-tagger,
+  #       port-logs,
+  #     ]
+  #   if: always()
+  #   uses: ./.github/workflows/notify-events-new.yaml
+  #   with:
+  #     state: ${{ needs.workflow-summary.outputs.state }}
+  #     title: "CD: ${{ github.repository }} - Workflow completed"
+  #     message: >
+  #       Workflow: ${{ github.workflow }}
+  #       Run: ${{ github.run_id }}
+  #       Actor: ${{ github.triggering_actor || github.actor }}
+  #       Result:
+  #       generate-release-tag=${{ needs.generate-release-tag.result }},
+  #       build-publish-docker=${{ needs.build-publish-docker.result }},
+  #       chart-tagger=${{ needs.chart-tagger.result }},
+  #       port-logs=${{ needs.port-logs.result }}
+  #   secrets:
+  #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
